# Application for Grafana
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "8.9.0"  # Adjust the version as needed
    helm:
      parameters:
        - name: service.type
          value: NodePort    
        - name: persistence.enabled
          value: "false"     
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring   
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
---
# Application for Loki (Logs)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "2.8.0"  
    helm:
      parameters:
        - name: persistence.enabled
          value: "false"   
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
# Application for Tempo (Traces)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "1.18.1 "  
    helm:
      parameters:
        - name: service.type
          value: ClusterIP  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
# Application for Mimir (Metrics)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-distributed
  namespace: argocd
spec:
  project: default
  source:
    chart: mimir-distributed         
    repoURL: https://grafana.github.io/helm-charts  
    targetRevision: "5.6.0"  
    helm:
      parameters:
        - name: service.type
          value: ClusterIP  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
# ------------------------------------------------------------
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-user/ArgoCDRepo.git'
    targetRevision: main
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
